#!/bin/bash
mkdir -p ./nodes

printf "%b" "#!/bin/bash

PHOENIX_NAME=samplephoenix \\
  ELIXIR_VERSION=0.15.1 \\
  PHOENIX_REPO=git@github.com:capbash/samplephoenix.git \\
  ./bits/phoenix/install
" > ./nodes/phoenix

chmod 755 ./nodes/phoenix

capbash install deploykeys
capbash install git
capbash install docker
capbash install elixir
