#!/bin/bash
mkdir -p ./nodes

printf "%b" "#!/bin/bash

PHOENIX_NAME=samplephoenix \\
  PHOENIX_REPO=git@github.com:aforward/samplephoenix.git \\
  ./submodules/phoenix/install
" > ./nodes/phoenix

chmod 755 ./nodes/phoenix

capbash install deploykeys
capbash install git
capbash install docker
capbash install elixir
