#!/bin/bash
source ./bits/bootstrap/logging

#-----------
# Configurations
#-----------

ELIXIR_VERSION=${ELIXIR_VERSION-v1.0.4}
PHOENIX_VERSION=${PHOENIX_VERSION-v0.13.0}
PHOENIX_INTERNAL_VERSION=$(echo $PHOENIX_VERSION | cut -d'v' -f 2)
PHOENIX_DISPLAY=${PHOENIX_DISPLAY-standalone} # or internal

LOG_DIR=${LOG_DIR-/var/log}
SRC_DIR=${SRC_DIR-/var/src}
export PHOENIX_LOG_DIR=${PHOENIX_LOG_DIR-$LOG_DIR/phoenix}
export PHOENIX_SRC_DIR=${PHOENIX_SRC_DIR-$SRC_DIR/phoenix}

LAUNCHER_OWNER=${LAUNCHER_OWNER-$USER}
export LAUNCHER_DIR=${LAUNCHER_DIR-/var/local}
export PHOENIX_LAUNCHER_DIR=${PHOENIX_LAUNCHER_DIR-$LAUNCHER_DIR/phoenix/$PHOENIX_VERSION}

#-----------
# Install Script
#-----------

if [[ "$PHOENIX_DISPLAY" == "standalone" ]]; then
  notify "Install Phoenix (p $PHOENIX_VERSION / e $ELIXIR_VERSION) ..."
else
  notify "  -- Install Phoenix (p $PHOENIX_VERSION / e $ELIXIR_VERSION) ..."
fi

OWNER=$LAUNCHER_OWNER ./bits/bootstrap/mkdir \
  LAUNCHER_DIR \
  PHOENIX_LAUNCHER_DIR \
  $PHOENIX_LAUNCHER_DIR/src \
  $PHOENIX_LAUNCHER_DIR/bin

OWNER=$LAUNCHER_OWNER TEMPLATE=./bits/phoenix/files/bin LOCATION=$PHOENIX_LAUNCHER_DIR/bin \
  ./bits/docker/copyallif

SRC_NAME=phoenix_new-$PHOENIX_INTERNAL_VERSION.ez SRC_DIR=${PHOENIX_LAUNCHER_DIR}/src \
  NAME="Phoenix ${PHOENIX_VERSION}" \
  REMOTE_URL=https://github.com/phoenixframework/phoenix/releases/download/$PHOENIX_VERSION \
  ./bits/bootstrap/wget

OWNER=$LAUNCHER_OWNER LAUNCHER_DIR=$PHOENIX_LAUNCHER_DIR BIT=phoenix ./bits/docker/copydockerfile \
  @ELIXIR_VERSION@ $ELIXIR_VERSION \
  @PHOENIX_VERSION@ $PHOENIX_VERSION \
  @PHOENIX_INTERNAL_VERSION@ $PHOENIX_INTERNAL_VERSION

LAUNCHER_DIR=$PHOENIX_LAUNCHER_DIR NAME=phoenix VERSION=${PHOENIX_VERSION} ./bits/docker/build
NAME=phoenix DIR=$PHOENIX_LAUNCHER_DIR BIT=phoenix VERSION=${PHOENIX_VERSION} ./bits/docker/helpers

if [[ "$PHOENIX_DISPLAY" == "standalone" ]]; then
  notify "DONE, Install Phoenix."
else
  notify "  -- DONE, Install Phoenix."
fi
