#!/bin/bash

#-----------
# Configurations
#-----------

ELIXIR_VERSION=${ELIXIR_VERSION-master}
NGINX_SITES_ENABLED_DIR=${NGINX_SITES_ENABLED_DIR-/etc/nginx/sites-enabled}
NGINX_LOG_DIR=${NGINX_LOG_DIR-/var/log/nginx}
PHOENIX_PROXY_PORT=${PHOENIX_PROXY_PORT-80}
PHOENIX_NAME=${PHOENIX_NAME-samplephoenix}
PHOENIX_DIR=${PHOENIX_DIR-/var/apps/${PHOENIX_NAME}}
PHOENIX_REPO=${PHOENIX_REPO-git@github.com:aforward/samplephoenix.git}
PHOENIX_HTTP_PORT=${PHOENIX_HTTP_PORT-80}
PHOENIX_SSL_PORT=${PHOENIX_SSL_PORT-443}
PHOENIX_MODE=${PHOENIX_MODE:as_is} # supports as_is, nginx
PHOENIX_APP_PORT=${PHOENIX_INTERNAL_PORT-$PHOENIX_HTTP_PORT}
PHOENIX_SERVER_NAMES=${PHOENIX_SERVER_NAMES-_}

#-----------
# Install Script
#-----------

ELIXIR_VERSION=$ELIXIR_VERSION ./submodules/elixir/install

mkdir -p $PHOENIX_DIR
cp ./submodules/phoenix/files/phoenix.dockerfile $PHOENIX_DIR/Dockerfile
sed -i s/@ELIXIR_VERSION@/$ELIXIR_VERSION/g $PHOENIX_DIR/Dockerfile
sed -i s/@PHOENIX_PROXY_PORT@/$PHOENIX_PROXY_PORT/g $PHOENIX_DIR/Dockerfile

GIT_URL=$PHOENIX_REPO \
  GIT_BASE_DIR=$PHOENIX_DIR \
  GIT_REPO_NAME=webapp \
  ./submodules/git/install

printf "%b" "
webapp/.git
webapp/.gitignore
webapp/test
webapp/README.md
" > $PHOENIX_DIR/.dockerignore

(cd $PHOENIX_DIR && docker build -t ${PHOENIX_NAME} .)


NAME=$PHOENIX_NAME DIR=$PHOENIX_DIR ./submodules/docker/ip
NAME=$PHOENIX_NAME DIR=$PHOENIX_DIR ./submodules/docker/idempot
NAME=$PHOENIX_NAME DIR=$PHOENIX_DIR ./submodules/docker/stop

printf "%b" "#!/bin/bash
docker run -i -t -p 7623:80 -p 7624:443 ${PHOENIX_NAME} /bin/bash
" > $PHOENIX_DIR/debug

printf "%b" "#!/bin/bash
docker rm ${PHOENIX_NAME} > /dev/num
docker run -d -t -p ${PHOENIX_HTTP_PORT}:80 -p ${PHOENIX_SSL_PORT}:443 --name ${PHOENIX_NAME} ${PHOENIX_NAME}
IP=\$(/var/apps/${PHOENIX_NAME}/ip)

if [[ \"\$IP\" == '' ]]; then
  echo 'No IP address assigned when starting MYSQL, not sure what went wrong.'
  exit 1
fi

if [[ \"\`cat /etc/hosts | grep ${PHOENIX_NAME}.local\`\" == '' ]]; then
  echo \"Adding ${PHOENIX_NAME}.local (\$IP) to /etc/hosts\"
  echo \"\$IP ${PHOENIX_NAME}.local\" >> /etc/hosts
else
  echo \"Updating ${PHOENIX_NAME}.local (\$IP) in /etc/hosts\"
  sed -i \"s|.*${PHOENIX_NAME}.local|\$IP ${PHOENIX_NAME}.local|g\" /etc/hosts
fi
" > $PHOENIX_DIR/start

if [[ "$PHOENIX_MODE" == "nginx" ]]; then
  cp ./submodules/phoenix/files/nginx.conf $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  sed -i "s|@PHOENIX_NAME@|$PHOENIX_NAME|g" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  sed -i "s|@PHOENIX_APP_PORT@|$PHOENIX_APP_PORT|g" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  sed -i "s|@PHOENIX_SERVER_NAMES@|$PHOENIX_SERVER_NAMES|g" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  sed -i "s|@SERVER_LOGS@|$NGINX_LOG_DIR|g" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  echo "$PHOENIX_DIR/sync_ip" >> $PHOENIX_DIR/start
  echo "$PHOENIX_DIR/sync_ip" >> $PHOENIX_DIR/stop
  echo "$PHOENIX_DIR/sync_ip" >> $PHOENIX_DIR/idempot
fi

  printf "%b" "#!/bin/bash
IP=\$(/var/apps/${PHOENIX_NAME}/ip)
if [[ \"\$IP\" == '' ]]; then
  echo \"Resetting $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME IP 127.0.0.1\"
  sed -i \"s|[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*|127.0.0.1|g\" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
else
  echo \"Updating $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME IP \$IP\"
  sed -i \"s|[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*|\$IP|g\" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
fi
touch /var/apps/nginx_reload
" > $PHOENIX_DIR/sync_ip



chmod 755 $PHOENIX_DIR/start
chmod 755 $PHOENIX_DIR/debug
chmod 755 $PHOENIX_DIR/sync_ip
