#!/bin/bash
source ./submodules/bootstrap/logging

#-----------
# Configurations
#-----------

ELIXIR_VERSION=${ELIXIR_VERSION-v1.0.0}
NGINX_SITES_ENABLED_DIR=${NGINX_SITES_ENABLED_DIR-/etc/nginx/sites-enabled}
NGINX_LOG_DIR=${NGINX_LOG_DIR-/var/log/nginx}
PHOENIX_PROXY_PORT=${PHOENIX_PROXY_PORT-80}
PHOENIX_LAUNCHER_DIR=${PHOENIX_LAUNCHER_DIR-/var/local/apps/${PHOENIX_NAME}}
PHOENIX_REPO=${PHOENIX_REPO-git@github.com:aforward/samplephoenix.git}
PHOENIX_MODE=${PHOENIX_MODE:as_is} # supports as_is, nginx
PHOENIX_APP_PORT=${PHOENIX_INTERNAL_PORT-$PHOENIX_HTTP_PORT}
PHOENIX_SERVER_NAMES=${PHOENIX_SERVER_NAMES-_}

export PHOENIX_HTTP_PORT=${PHOENIX_HTTP_PORT-80}
export PHOENIX_SSL_PORT=${PHOENIX_SSL_PORT-443}
export PHOENIX_NAME=${PHOENIX_NAME-samplephoenix}

#-----------
# Install Script
#-----------

ELIXIR_VERSION=$ELIXIR_VERSION ./submodules/elixir/install

mkdir -p $PHOENIX_LAUNCHER_DIR
cp ./submodules/phoenix/files/phoenix.dockerfile $PHOENIX_LAUNCHER_DIR/Dockerfile
sed -i s/@ELIXIR_VERSION@/$ELIXIR_VERSION/g $PHOENIX_LAUNCHER_DIR/Dockerfile
sed -i s/@PHOENIX_PROXY_PORT@/$PHOENIX_PROXY_PORT/g $PHOENIX_LAUNCHER_DIR/Dockerfile

GIT_URL=$PHOENIX_REPO \
  GIT_APPS_DIR=$PHOENIX_LAUNCHER_DIR \
  GIT_REPO_NAME=webapp \
  ./submodules/git/install

printf "%b" "
webapp/.git
webapp/.gitignore
webapp/test
webapp/README.md
" > $PHOENIX_LAUNCHER_DIR/.dockerignore

LAUNCHER_DIR=$PHOENIX_LAUNCHER_DIR NAME=${PHOENIX_NAME} ./submodules/docker/build

NAME=$PHOENIX_NAME DIR=$PHOENIX_LAUNCHER_DIR \
  START=./submodules/phoenix/files/_start \
  DEBUG=./submodules/phoenix/files/_debug \
  ./submodules/docker/helpers

if [[ "$PHOENIX_MODE" == "nginx" ]]; then
  cp ./submodules/phoenix/files/nginx.conf $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  sed -i "s|@PHOENIX_NAME@|$PHOENIX_NAME|g" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  sed -i "s|@PHOENIX_APP_PORT@|$PHOENIX_APP_PORT|g" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  sed -i "s|@PHOENIX_SERVER_NAMES@|$PHOENIX_SERVER_NAMES|g" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  sed -i "s|@SERVER_LOGS@|$NGINX_LOG_DIR|g" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
  echo "$PHOENIX_LAUNCHER_DIR/sync_ip" >> $PHOENIX_LAUNCHER_DIR/start
  echo "$PHOENIX_LAUNCHER_DIR/sync_ip" >> $PHOENIX_LAUNCHER_DIR/stop
  echo "$PHOENIX_LAUNCHER_DIR/sync_ip" >> $PHOENIX_LAUNCHER_DIR/idempot
fi

  printf "%b" "#!/bin/bash
source /usr/local/bin/logging
IP=\$(/var/local/apps/${PHOENIX_NAME}/ip)
if [[ \"\$IP\" == '' ]]; then
  debug \"Resetting $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME IP 127.0.0.1\"
  sed -i \"s|[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*|127.0.0.1|g\" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
else
  debug \"Updating $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME IP \$IP\"
  sed -i \"s|[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*|\$IP|g\" $NGINX_SITES_ENABLED_DIR/$PHOENIX_NAME
fi
touch /var/local/apps/nginx_reload
" > $PHOENIX_LAUNCHER_DIR/sync_ip

chmod 755 $PHOENIX_LAUNCHER_DIR/start
chmod 755 $PHOENIX_LAUNCHER_DIR/debug
chmod 755 $PHOENIX_LAUNCHER_DIR/sync_ip
